- .gitignore
- styles/_classifier.scss
> dedupe styles to fix premium labels

- styles/_concept.scss
- styles/_myft-card.scss
- templates/concept.html
Depends on https://github.com/Financial-Times/next-myft-page/pull/1528 for the excess story count.
> Implement latest design iteration

- styles/_concept.scss
- styles/_myft-card.scss
> Enmatchen paddings, colours, etc to design

- styles/_myft-card.scss
> Margins are controlled from the app

- styles/_classifier.scss
- styles/_concept.scss
- styles/_myft-card.scss
> Linting fixes

- bower.json
> Bump n-myft-ui to version 10

- templates/concept.html
> Update pin button to use o-button

- styles/_myft-card.scss
- templates/concept.html
> Update pinning markup

- templates/concept.html
> Add data-trackable attr to pin button

- styles/_myft-card.scss
- templates/concept.html
> Move pin button code to n-myft-ui

- styles/_myft-card.scss
> Padding at the bottom to match footer top padding

- styles/_concept.scss
- styles/_myft-card.scss
- templates/concept.html
loose:
toit:
Awaiting confirmation and co-jiggling before merging.
> Tighten up topic cards

- styles/_myft-card.scss
- templates/concept.html
> Update design for empty concept card

- templates/concept.html
https://www.youtube.com/watch?v=RkEXGgdqMz8
> Use new o-date format of time-ago-abbreviated

- styles/_concept.scss
- templates/concept.html
https://trello.com/c/F6SLKDpB/48-dactechlistsissue01
No visual changes.
> Address accessibility issues

- bower.json
Picks up on #26 to unblock updating next-stream-page and next-myft-page
🐿 v2.5.16
> Bump n-myft-ui to v12

- bower.json
- templates/concept.html
> Use new entry points for n-myft-ui

- templates/concept.html
> Use new path to instant-alert template.

- bower.json
Update to n-myft-ui@16 to avoid version conflicts in apps that depend on both n-topic-card and n-myft-ui.
> Use n-myft-ui@16

- templates/concept.html
So that Knowledge Builder in the article will pick up the relevant topic
> Adds Knowledge Builder concept to article links

- demos/demo.html
- demos/fixtures.json
- demos/src/main.scss
> Fix styles in the demo

- bower.json
- templates/concept.html
Does what it says on the tin.
🐿 v2.11.0
> Update myft-ui follow-button template location

- bower.json
- demos/fixtures.json
> bump n-myft-ui

- bower.json
Yay Bower conflicts! I can't install the latest n-myft-ui beta in
front-page until it's been updated here.
> Use the latest n-myft-ui

- bower.json
Update n-topic-card to depoy with non beta version of n-myft-ui
> Use full version of n-myft-ui not the beta release 🐿 v2.12.5

- bower.json
- main.scss
Removes n-image as a bower dependency as it isn't used anywhere in this component.
> remove dependency n-image

- bower.json
Upgrade to n-myft-ui.
This new version has:
- upgrade to node 12
- publish again package to npm
> bump n-myft-ui to 23.0.1

- .circleci/config.yml
- package.json
Our internal tools do not support yet node 14 so we downgrade to 12
> Downgrade to node 12

- package-lock.json
- package.json
set n-myft-ui as peer dependency as it make more sense to be like that
[request](https://github.com/Financial-Times/next-stream-page/pull/2925#discussion_r983617129)
> set n-myft-ui as peer dependency

- package-lock.json
- package.json
To apply [this n-myft-ui change](https://github.com/Financial-Times/n-myft-ui/pull/562)
|Before|After|
|---|---|
|![Screenshot 2023-02-06 at 13 05 43](https://user-images.githubusercontent.com/21194161/216982117-fd2ccef9-74fc-4468-8ffd-00e034783e0a.png)|![Screenshot 2023-02-06 at 13 16 04](https://user-images.githubusercontent.com/21194161/216982131-f0e33594-1cdd-4ed6-9585-f32bae2f3615.png)|
> Upgrade n-myft-ui to v30
